// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbxDjeeMSQIuVMYcLVqUP7BaTFgY1WHLE',
    appId: '1:605881990878:web:5ee9af3fd816e87b768c4f',
    messagingSenderId: '605881990878',
    projectId: 'flipkarthealth-bc871',
    authDomain: 'flipkarthealth-bc871.firebaseapp.com',
    storageBucket: 'flipkarthealth-bc871.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCGkhQSfNtxsQ5_VyxE5VGpTq8eswMbOd8',
    appId: '1:605881990878:android:cb014148a4d780a4768c4f',
    messagingSenderId: '605881990878',
    projectId: 'flipkarthealth-bc871',
    storageBucket: 'flipkarthealth-bc871.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2vCM1HB4GsMfdXwOfssXEmTJNsCKkWRU',
    appId: '1:605881990878:ios:313dee3398b5bbe8768c4f',
    messagingSenderId: '605881990878',
    projectId: 'flipkarthealth-bc871',
    storageBucket: 'flipkarthealth-bc871.appspot.com',
    androidClientId: '605881990878-0686tfqfi98qitntr301hujcg502er90.apps.googleusercontent.com',
    iosClientId: '605881990878-pp56stko8jn4kdclr0onalv977i3hakg.apps.googleusercontent.com',
    iosBundleId: 'com.example.health',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD2vCM1HB4GsMfdXwOfssXEmTJNsCKkWRU',
    appId: '1:605881990878:ios:976fd3eae060a7f1768c4f',
    messagingSenderId: '605881990878',
    projectId: 'flipkarthealth-bc871',
    storageBucket: 'flipkarthealth-bc871.appspot.com',
    androidClientId: '605881990878-0686tfqfi98qitntr301hujcg502er90.apps.googleusercontent.com',
    iosClientId: '605881990878-08teefi41c6h7vd7jg7fla1vboerceq7.apps.googleusercontent.com',
    iosBundleId: 'com.example.health.RunnerTests',
  );
}
